-- Set Root Password
UPDATE mysql.user SET Password = PASSWORD('$MARIADB_ROOT_PW') WHERE User = '$MARIADB_ROOT';

-- Create DB
CREATE DATABASE IF NOT EXISTS $MARIADB_WP_DB;

-- Create User
CREATE USER '$MARIADB_USER'@'%' IDENTIFIED BY '$MARIADB_USER_PW';

-- Grant User Privileges
GRANT ALL PRIVILEGES ON $MARIADB_WP_DB.* TO '$MARIADB_USER'@'%';

-- Apply
FLUSH PRIVILEGES;