services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mariadb-wordpress

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - wp_data:/var/www/wordpress
    networks:
      - mariadb-wordpress
      - nginx-wordpress

  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    env_file: .env
    ports:
      - 443:443
    volumes:
      - wp_data:/var/www/wordpress
    networks:
      - nginx-wordpress


volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/db_data
    name: db_data

  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wp_data
    name: wp_data


networks:
  mariadb-wordpress:
  nginx-wordpress: